<?php
/**
 * @var \Elogic\StoreLocator\Block\Store $block
 */

$store = $block->getStore();

?>

<div class="store">
    <div id="store-<?= $store->getId() ?>" class="store">
        <div class="description">
            <h3><?= __("Description: ") ?></h3>
            <span><?= $store->getDescription() ?></span>
        </div>
        <div class="address">
            <h3><?= __("Address: ") ?></h3>
            <span><?= $store->getAddress() ?></span>
        </div>
        <div class="image">
            <h3><?= __("Image: ") ?></h3>
            <img src="<?= '/pub/media/elogic/base_path/' . $store->getImage() ?>" alt="Store image" width="" height="400"/>
        </div>
        <div class="longitude">
            <h3><?= __("Longitude: ") ?></h3>
            <span><?= $store->getLongitude() ?></span>
        </div>
        <div class="latitude">
            <h3><?= __("Latitude: ")?></h3>
            <span><?= $store->getLatitude() ?></span>
        </div>

    </div>
</div>
