<?php
/**
 * @var $data StoreViewModel
 */

use Elogic\StoreLocator\ViewModel\StoreViewModel;

$store = $data->getStore();
?>
<div class="store">
    <div id="store-<?= $store->getId() ?>" class="store">
        <div class="description">
            <h3><?= __("Description: ") ?></h3>
            <span><?= $store->getDescription() ?></span>
        </div>
    <div id="store-<?= $store->url ?>" class="store">
        <div class="description">
            <h3><?= __("Description: ") ?></h3>
            <span><?= $store->getDescription() ?></span>
        </div>
        <div class="address">
            <h3><?= __("Address: ") ?></h3>
            <span><?= $store->getAddress() ?></span>
        </div>
        <div class="image">
            <h3><?= __("Image: ") ?></h3>
            <img src="<?= 'elogic/base_path/' . $store->getImage() ?>" width="300" height="400"/>
        </div>
        <div class="longitude">
            <h3><?= __("Longitude: ") ?></h3>
            <span><?= $store->getLongitude() ?></span>
        </div>
        <div class="latitude">
            <h3><?= __("Latitude: ")?></h3>
            <span><?= $store->getLatitude() ?></span>
        </div>

    </div>
</div>
